#! /bin/sh

xsetroot -cursor_name left_ptr &

/home/bauer/.fehbg
picom --vsync --config /home/bauer/.config/picom/picom.conf -b
sxhkd &

bspc monitor -d I II III IV V

bspc config border_width            1
bspc config window_gap              10

bspc config bottom_padding          20

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config focus_follows_pointer   true

bspc config pointer_modifier mod1
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move

bspc rule -a Zathura state=tiled

